[build]
  command = "npx convex deploy --cmd 'pnpm run build'"
  publish = "dist/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"
  targetPort = 3000
  port = 8888